version: '2'
services:
    boncmd6-app:
        image: boncmd6
        external_links:
            - boncmd6-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/boncmd6?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    boncmd6-mysql:
        extends:
            file: mysql.yml
            service: boncmd6-mysql
